In [1]:
import os
import sys
sys.path.append(os.path.abspath('..'))

import numpy as np
import matplotlib.pyplot as plt
import modules.rcnn.box as box

In [4]:
H = 400
W = 400

gt_box = np.array([
    [0.25*W,0.25*H,0.25*W,0.25*H],
    [0.5*W,0.5*H,0.25*W,0.25*H]
])

gt_scale = gt_box/H

anchors = np.array([
    [0.1,0.1,0.1,0.1],
    [0.2,0.2,0.25,0.25],
    [0.5,0.5,0.1,0.1],
    [0.55,0.55,0.2,0.2],
])

print(gt_box)
print(gt_scale)
print(anchors)

[[100. 100. 100. 100.]
 [200. 200. 100. 100.]]
[[0.25 0.25 0.25 0.25]
 [0.5  0.5  0.25 0.25]]
[[0.1  0.1  0.1  0.1 ]
 [0.2  0.2  0.25 0.25]
 [0.5  0.5  0.1  0.1 ]
 [0.55 0.55 0.2  0.2 ]]


In [5]:
ious = box.iou(anchors,gt_scale)
print(ious.shape)
print(ious)

(4, 2)
[[0.00869565 0.        ]
 [0.47058824 0.        ]
 [0.         0.16      ]
 [0.         0.42608696]]
